---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.userdetails
    config:
        locations:
            - file:/data/userdetails/config/userdetails-config.properties
            - file:/data/userdetails/config/userdetails-config.yml
            - file:/data/userdetails/config/userdetails-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugins:
        twitterbootstrap:
            fixtaglib: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    data:
      redis:
        repositories:
          enabled: false
    session:
      enabled: false
      store-type: none # Spring Session support disabled by default.
#        disable-redis-config-action: false
      grails:
        mutableAttributes:
          - SYNCHRONIZER_TOKENS_HOLDER
    jmx:
      unique-names: true
    devtools:
      restart:
        additional-exclude:
          - '*.gsp'
          - '**/*.gsp'
          - '*.gson'
          - '**/*.gson'
          - 'logback.groovy'
          - '*.properties'
server:
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      port-header: x-forwarded-port
      remote-ip-header: x-forwarded-for
      protocol-header-https-value: https

---
grails:
    mime:
        use:
            accept:
                header: true
        disable:
            accept:
                header:
                    userAgents: []
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    databinding:
        convertEmptyStringsToNull: false
    cache:
        enabled: true
        ehcache:
            cacheManagerName: 'userdetails-cache-manager'
            ehcacheXmlLocation: 'classpath:userdetails-ehcache.xml'
            reloadable: false

security:
    core:
        uri-filter-pattern: ['/admin/*','/registration/editAccount','/my-profile','/my-profile/','/myprofile/','/myprofile','/profile/*','/admin/','/admin','/registration/update','/registration/update/*','/monitoring','/monitoring/*','/registration/disableAccount/*','/registration/disableAccount','/admin/admin/downloadUsersCsvFile','/alaAdmin/*']
        optional-filter-pattern: ['/']
    cas:
      enabled: false
    oidc:
      enabled: true
      scope: openid profile email ala roles
      allowUnsignedIdTokens: true # Disable once CAS no longer suggests the none algorithm
    jwt:
      enabled: true
      fallbackToLegacyBehaviour: true # Reset to false once legacy api keys no longer supported
    filterOrder: 0
#    basic:
#        enabled: true
#        authorizeMode: role
#        realm: ALA User Details
#        path:
#          - /status/**
webservice:
  jwt: true
  scope: "openid"

# Spring Actuator Endpoints are Disabled by Default
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      defaults:
        enabled: true
      jdbc:
        enabled: true
      redis:
        enabled: false # set to true for HA environments
      mongo:
        enabled: false # set to true for HA environments
    web:
      base-path: "/actuator"
      exposure:
        include:
        - health
        - info
spring:
    boot:
        admin:
            client:
                enabled: false
                service-base-url: ${serverURL}
                metadata:
                    user:
                        name: ${security.user.name}
                        password: ${security.user.password}

password:
    encoder: bcrypt # or legacy
bcrypt:
    strength: 10



attributes:
    states:
        path: classpath:states.json
    affiliations:
      enabled: false

skin:
    layout: "ala-main"
    fluidLayout: true
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
privacyPolicy: "https://www.ala.org.au/privacy-policy/"
termsOfUse: "https://www.ala.org.au/terms-of-use/"

logo:
  biocollect: https://www.ala.org.au/app/uploads/2019/05/BioCollect-icon-1.png
  spatialportal: https://www.ala.org.au/app/uploads/2019/06/19-0078_ALA_ICON_IconSuite_Spatial-Portal.svg
  digivol: https://www.ala.org.au/app/uploads/2019/04/specimen-icon.png
  specieslists: https://www.ala.org.au/app/uploads/2019/06/19-0078_ALA_ICON_IconSuite_Species-Lists.svg
  api: https://www.ala.org.au/app/uploads/2019/06/19-0078_ALA_ICON_IconSuite_Web-service-APIs.svg
  inaturalist: https://www.ala.org.au/app/uploads/2019/09/iNaturalist_logomark-alaBlack-icon.png
  sandbox: https://www.ala.org.au/app/uploads/2019/06/19-0078_ALA_ICON_IconSuite_Sandbox-1.svg
  downloads: https://www.ala.org.au/app/uploads/2019/06/19-0078_ALA_ICON_IconSuite_Download-Predefined-Datasets.svg
  flickr: https://upload.wikimedia.org/wikipedia/commons/3/31/Flickr_font_awesome.svg

oauth:
#  debug: true
  providers:
    flickr:
      enabled: true
      api: 'com.github.scribejava.apis.FlickrApi'
      key: "xxxxxxxxxxxxxxxxxxxxx"
      secret: "xxxxxxxxxxxxxxxxxxxxx"
      successUri: '/profile/flickrSuccess'
      failureUri: '/profile/flickrFail'
      callback: "xxxxxxxxxxxxx/yyyyyyyyyy/profile/flickrCallback"
    inaturalist:
      enabled: false
      api: 'au.org.ala.oauth.apis.InaturalistApi'
      key: 'xxxxxxxxxxxxxxxxxxxxx'
      secret: 'xxxxxxxxxxxxxxxxxxxxx'
      successUri: '/profile/inaturalistSuccess'
      failureUri: '/profile/inaturalistFailure'
      callback: 'xxxxxx/yyyyyyy/profile/inaturalistCallback'

inaturalist:
  name: iNaturalist Australia
  baseUrl: https://inaturalist.ala.org.au/
  searchQuery: data_resource_uid:dr1411
  sightingsSearchQuery: data_resource_uid:dr364

biocache:
  search:
    baseUrl: https://biocache.ala.org.au/occurrences/search

sightings:
  url: https://biocollect.ala.org.au/spotter

myData:
  url: https://sandbox.ala.org.au/tempDataResource/myData

biocollect:
  url: https://biocollect.ala.org.au/acsa/bioActivity/list?hub=acsa

openapi:
  title: UserDetails REST services
  description: REST services for interacting with the user details webapp
  terms: https://www.ala.org.au/terms
  contact:
    name: Support
    email: support@ala.org.au
  license:
    name: Mozilla Public License 1.1
    url: https://www.mozilla.org/en-US/MPL/1.1/
  version: '@info.app.version@'
  cachetimeoutms: 0
  components:
    security:
      oauth2:
        scopes:
          users/read: Read or list any or all user records
          users/write: Write to a user's record, eg update a user's attributes.

supportEmail: support-local@ala.org.au
homeUrl: https://www.ala.org.au
homeLogoUrl: https://www.ala.org.au/app/uploads/2020/06/ALA_Logo_Inline_RGB-300x63.png
mainTitle: Atlas of Living Australia (local)
emailSenderTitle: Atlas of Living Australia
emailSender: support@ala.org.au

markdown:
    removeHtml: true

# set to true to display more ALA registration messages
registration:
    showAlaMessage: false
    resetPasswordArticle:
    alertArticle:
    activationArticle:

recaptcha:
  baseUrl: https://www.google.com/recaptcha/api/
  siteKey:
  secretKey:

environments:
    development:
        grails:
            serverURL: "http://devt.ala.org.au:8080/userdetails"
            mail:
                host: "localhost"
                port: 1025
                username: postie.emailSender
        security:
            cas:
                appServerName: "http://devt.ala.org.au:8080"
    test:
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    production:
        grails:
            serverURL: "https://auth.ala.org.au/userdetails"
            mail:
                host: "localhost"
                port: 25
        security:
            cas:
                appServerName: "https://auth.ala.org.au"

---
hibernate:
    allow_update_outside_transaction: true # Hibernate 5 made transactions required to flush changes, set to true for backwards compat but should be set to false and bugs fixed in the future
    show_sql: false
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: true
        region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    type: "com.zaxxer.hikari.HikariDataSource"
    username:
    password:
    properties:
#        # http://www.grails.org/doc/latest/guide/single.html#dataSource
#        # see http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes for more
#        timeBetweenEvictionRunsMillis: 60000 # milliseconds (default: 5000)
#        testOnBorrow: true # default: false
#        testOnReturn: false # default: false
#        testWhileIdle: true # default: false
#        validationQuery: "SELECT 1" # default: null
#        validationQueryTimeout: 10 # seconds (default: -1 i.e. disabled)
#        validationInterval: 30000 # milliseconds, default is 30000 (30 seconds)
#        removeAbandoned: true # # default: false
#        removeAbandonedTimeout: 300 # seconds (default: 60)
#        logAbandoned: true # adds some overhead to every borrow from the pool, disable if it becomes a performance issue
#        logValidationErrors: true # default: false, logs validation errors at SEVERE
#        # NOTE: removeAbandoned: true OR testWhileIdle: true enables the Pool Cleaner. There is a bug with the
#        # pool cleaner which causes deadlocks when using older mysql jdbc drivers. This configuration has been
#        # tested successfully with mysql:mysql-connector-java:5.1.34.
#        # mysql jdbc connection properties - see http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
#        dbProperties:
#            autoReconnect: true
#            connectTimeout: 0
#            useUnicode: true
#            characterEncoding: "UTF-8"

environments:
    development:
        dataSource:
            dbCreate: "validate"
            url: "jdbc:mysql://localhost/emmet"
            username: "root"
            password: "password"
    test:
        dataSource:
            dbCreate: "create-drop"
            pooled: true
            driverClassName: "org.h2.Driver"
            username: "sa"
            password: ""
    production:
        dataSource:
            dbCreate: "validate"

# Allow to disable some tools for non-ALA Portals
myProfile:
  useDigiVol: true
  useSandbox: true
  useBiocollect: true
